Backend:
  - changed-files:
      paths:
        - "Server/**"

Frontend:
  - changed-files:
      paths:
        - "Client/**"

FullStack:
  - changed-files:
      all:
        - patterns:
            - "Server/**"
        - patterns:
            - "Client/**"
