// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LotteryApp")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "LotteryApp");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DataAccess.Entities.Finance.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Wallets", "LotteryApp");
                });

            modelBuilder.Entity("DataAccess.Entities.Auth.Admin", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Auth.User");

                    b.ToTable("Admins", "LotteryApp");
                });

            modelBuilder.Entity("DataAccess.Entities.Auth.Player", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Auth.User");

                    b.ToTable("Players", "LotteryApp");
                });

            modelBuilder.Entity("DataAccess.Entities.Finance.Wallet", b =>
                {
                    b.HasOne("DataAccess.Entities.Auth.Player", "Player")
                        .WithOne("Wallet")
                        .HasForeignKey("DataAccess.Entities.Finance.Wallet", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DataAccess.Entities.Auth.Admin", b =>
                {
                    b.HasOne("DataAccess.Entities.Auth.User", null)
                        .WithOne()
                        .HasForeignKey("DataAccess.Entities.Auth.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Auth.Player", b =>
                {
                    b.HasOne("DataAccess.Entities.Auth.User", null)
                        .WithOne()
                        .HasForeignKey("DataAccess.Entities.Auth.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Auth.Player", b =>
                {
                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
